basePath: /api
consumes:
  - application/json
definitions:
  Actor:
    properties:
      bio:
        format: string
        type: string
      birthday:
        format: date
        type: string
      id:
        format: int32
        type: integer
      image:
        format: string
        type: string
      name:
        format: string
        type: string
    type: object
  Character:
    properties:
      desc:
        format: string
        type: string
      id:
        format: int32
        type: integer
      name:
        format: string
        type: string
      stories:
        format: string
        type: string
      thumbnail:
        format: string
        type: string
    type: object
  ComicSeries:
    properties:
      desc:
        format: string
        type: string
      end_year:
        format: int32
        type: integer
      id:
        format: int32
        type: integer
      rating:
        format: float
        type: number
      runtime:
        format: int32
        type: integer
      start_year:
        format: int32
        type: integer
      thumbnail:
        format: string
        type: string
      title:
        format: string
        type: string
    type: object
  Event:
    properties:
      creators:
        format: string
        type: string
      desc:
        format: string
        type: string
      id:
        format: int32
        type: integer
      start:
        format: date
        type: string
      thumbnail:
        format: string
        type: string
      title:
        format: string
        type: string
    type: object
  Movie:
    properties:
      adult:
        format: bool
        type: boolean
      id:
        format: int32
        type: integer
      lang:
        format: string
        type: string
      overview:
        format: string
        type: string
      poster_path:
        format: string
        type: string
      rating:
        format: float
        type: number
      release_date:
        format: date
        type: string
      runtime:
        format: int32
        type: integer
      title:
        format: string
        type: string
    type: object
  TvShow:
    properties:
      id:
        format: int32
        type: integer
      last_air_date:
        format: date
        type: string
      name:
        format: string
        type: string
      num_episodes:
        format: int32
        type: integer
      num_seasons:
        format: int32
        type: integer
      overview:
        format: string
        type: string
      poster_path:
        format: string
        type: string
      rating:
        format: float
        type: number
    type: object
host: marvelus.me
info: {
  "title" : "marvelus",
  "version" : "0.1"
}
paths:
  /actor:
    get:
      parameters:
        - description: searchjson
          in: query
          name: q
          type: string
      responses:
        '200':
          description: List actor
          schema:
            items:
              $ref: '#/definitions/Actor'
            title: actor
            type: array
      tags:
        - Actor
  '/actor/{actorId}':
    get:
      parameters:
        - description: ID of Actor
          in: path
          name: actorId
          required: true
          type: integer
      responses:
        '200':
          description: Success actor
          schema:
            $ref: '#/definitions/Actor'
            title: actor
      tags:
        - Actor
  /character:
    get:
      parameters:
        - description: searchjson
          in: query
          name: q
          type: string
      responses:
        '200':
          description: List character
          schema:
            items:
              $ref: '#/definitions/Character'
            title: character
            type: array
      tags:
        - Character
  '/character/{characterId}':
    get:
      parameters:
        - description: ID of Character
          in: path
          name: characterId
          required: true
          type: integer
      responses:
        '200':
          description: Success character
          schema:
            $ref: '#/definitions/Character'
            title: character
      tags:
        - Character
  /comic_series:
    get:
      parameters:
        - description: searchjson
          in: query
          name: q
          type: string
      responses:
        '200':
          description: List comic_series
          schema:
            items:
              $ref: '#/definitions/ComicSeries'
            title: comic_series
            type: array
      tags:
        - ComicSeries
  '/comic_series/{comicseriesId}':
    get:
      parameters:
        - description: ID of ComicSeries
          in: path
          name: comicseriesId
          required: true
          type: integer
      responses:
        '200':
          description: Success comic_series
          schema:
            $ref: '#/definitions/ComicSeries'
            title: comic_series
      tags:
        - ComicSeries
  /event:
    get:
      parameters:
        - description: searchjson
          in: query
          name: q
          type: string
      responses:
        '200':
          description: List event
          schema:
            items:
              $ref: '#/definitions/Event'
            title: event
            type: array
      tags:
        - Event
  '/event/{eventId}':
    get:
      parameters:
        - description: ID of Event
          in: path
          name: eventId
          required: true
          type: integer
      responses:
        '200':
          description: Success event
          schema:
            $ref: '#/definitions/Event'
            title: event
      tags:
        - Event
  /movie:
    get:
      parameters:
        - description: searchjson
          in: query
          name: q
          type: string
      responses:
        '200':
          description: List movie
          schema:
            items:
              $ref: '#/definitions/Movie'
            title: movie
            type: array
      tags:
        - Movie
  '/movie/{movieId}':
    get:
      parameters:
        - description: ID of Movie
          in: path
          name: movieId
          required: true
          type: integer
      responses:
        '200':
          description: Success movie
          schema:
            $ref: '#/definitions/Movie'
            title: movie
      tags:
        - Movie
  /tv_show:
    get:
      parameters:
        - description: searchjson
          in: query
          name: q
          type: string
      responses:
        '200':
          description: List tv_show
          schema:
            items:
              $ref: '#/definitions/TvShow'
            title: tv_show
            type: array
      tags:
        - TvShow
  '/tv_show/{tvshowId}':
    get:
      parameters:
        - description: ID of TvShow
          in: path
          name: tvshowId
          required: true
          type: integer
      responses:
        '200':
          description: Success tv_show
          schema:
            $ref: '#/definitions/TvShow'
            title: tv_show
      tags:
        - TvShow
        
  '/search/actor':
    get:
      parameters:
        - description: Text to search for
          in: query
          name: query 
          required: true
          type: string
      responses:
        '200':
          description: List actor
          schema:
            items:
              $ref: '#/definitions/Actor'
            title: actor
            type: array
      tags:
        - Search

  '/search/character':
    get:
      parameters:
        - description: Text to search for
          in: query
          name: query 
          required: true
          type: string
      responses:
        '200':
          description: List character
          schema:
            items:
              $ref: '#/definitions/Character'
            title: character
            type: array
      tags:
        - Search


  '/search/comic_series':
    get:
      parameters:
        - description: Text to search for
          in: query
          name: query 
          required: true
          type: string
      responses:
        '200':
          description: List comic_series
          schema:
            items:
              $ref: '#/definitions/ComicSeries'
            title: comic_series
            type: array
      tags:
        - Search

  '/search/event':
    get:
      parameters:
        - description: Text to search for
          in: query
          name: query 
          required: true
          type: string
      responses:
        '200':
          description: List event
          schema:
            items:
              $ref: '#/definitions/Event'
            title: event
            type: array
      tags:
        - Search

  '/search/movie':
    get:
      parameters:
        - description: Text to search for
          in: query
          name: query 
          required: true
          type: string
      responses:
        '200':
          description: List movie
          schema:
            items:
              $ref: '#/definitions/Movie'
            title: movie
            type: array
      tags:
        - Search

  '/search/tvshow':
    get:
      parameters:
        - description: Text to search for
          in: query
          name: query 
          required: true
          type: string
      responses:
        '200':
          description: List tv_show
          schema:
            items:
              $ref: '#/definitions/TvShow'
            title: tv_show
            type: array
      tags:
        - Search

produces:
  - application/json
schemes:
  - http
  - https
swagger: '2.0'
tags:
  - name: Actor
  - name: Character
  - name: ComicSeries
  - name: Event
  - name: Movie
  - name: TvShow
  - name: Search