runtime: python27
api_version: 1
threadsafe: true

# [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: marvelus-180722:us-central1:marvelus-db-v1
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: password
# [END env_variables]

# [START beta_settings]
beta_settings:
    cloud_sql_instances: marvelus-180722:us-central1:marvelus-db-v1
# [END beta_settings]
libraries:
- name: MySQLdb
  version: "latest"

# [START handlers]
handlers:

- url: /.*
  script: main.app

# [END handlers]

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- env
- node_modules
- .git
