runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /vendor
  static_dir: vendor
- url: /css
  static_dir: static/css
- url: /.*
  script: main.app
# [END handlers]
