runtime: python27
api_version: 1
threadsafe: true

env_variables:
    CLOUDSQL_CONNECTION_NAME: marvelus-180722:us-central1:marvelus-db-v1
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: password

libraries:
- name: MySQLdb
  version: "latest"

# [START handlers]
handlers:
- url: /app/static
  static_dir: static
  application_readable: true
- url: /vendor
  static_dir: vendor
#- url: /css
#  static_dir: static/css
- url: /index
  static_files: build/index.html
  upload: build/index.html
- url: /.*
  script: main.app


- url: /static
  static_dir: build/static
  application_readable: true
# [END handlers]
